# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ucf.xdc

# IP: ip/hard_rom/hard_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hard_rom || ORIG_REF_NAME==hard_rom} -quiet] -quiet

# IP: ip/normal_rom/normal_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==normal_rom || ORIG_REF_NAME==normal_rom} -quiet] -quiet

# IP: ip/basic_rom/basic_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==basic_rom || ORIG_REF_NAME==basic_rom} -quiet] -quiet

# IP: ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: ip/blk_mem_gen_2_1/blk_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: ip/hard_rom/hard_rom_ooc.xdc

# XDC: ip/normal_rom/normal_rom_ooc.xdc

# XDC: ip/basic_rom/basic_rom_ooc.xdc

# XDC: ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc

# XDC: ip/blk_mem_gen_2_1/blk_mem_gen_2_ooc.xdc

# XDC: ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
