# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/alan/Desktop/Things/logic design/game/game.cache/wt} [current_project]
set_property parent.project_path {C:/Users/alan/Desktop/Things/logic design/game/game.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/alan/Desktop/Things/logic design/game/game.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/main.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/boll.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/basic.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/normal.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/hard.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/over.coe}}
add_files {{C:/Users/alan/Desktop/Things/logic design/game/coe/winner.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/bcd.v}
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/dispnumber.v}
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/vgac.v}
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/top.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/ADXL362Ctrl.vhd}
  {C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/new/SPI_If.vhd}
}
read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/hard_rom/hard_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/hard_rom/hard_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/normal_rom/normal_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/normal_rom/normal_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/basic_rom/basic_rom.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/basic_rom/basic_rom_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_2_1/blk_mem_gen_2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_2_1/blk_mem_gen_2_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc}}]

read_ip -quiet {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/alan/Desktop/Things/logic design/game/game.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/constrs_1/new/ucf.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/alan/Desktop/Things/logic design/game/game.srcs/constrs_1/new/ucf.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
